version: '3'
services:
  ncalayer:
    build: .
    ports:
      - '5900:5900'
    volumes:
      - /mnt:/mnt
      - /media:/media
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
